crackling/kipper: Add back libcneapiclient
TheMuppets/proprietary_vendor_wileyfox pull request #8
Opened 2017-01-24 04:12 UTC by tdm

Change-Id: I43742747586cd132584d5cf60f31645f674f0c20

2017-01-24 04:13 UTC, zwliew commented on kipper/kipper-vendor.mk
> +    vendor/wileyfox/kipper/proprietary/vendor/lib/libcneapiclient.so:system/vendor/lib/libcneapiclient.so \
You're adding the wrong path

2017-01-24 04:14 UTC, zwliew requested changes

2017-01-24 04:14 UTC, zwliew commented on kipper/kipper-vendor.mk
> +    vendor/wileyfox/kipper/proprietary/vendor/lib/libcneapiclient.so:system/vendor/lib/libcneapiclient.so \
This is the wrong path

2017-01-24 04:14 UTC, zwliew commented on crackling/crackling-vendor.mk
> +    vendor/wileyfox/crackling/proprietary/vendor/lib/libcneapiclient.so:system/vendor/lib/libcneapiclient.so \
This is the wrong path as well

2017-01-24 04:17 UTC, tdm commented
Sorry, how is this the wrong path?

2017-01-24 04:19 UTC, zwliew commented
Oh nevermind, I didn't realise that the 32-bit libcneapiclient lib was already present in the vendor tree but wasn't being installed.

2017-01-24 04:20 UTC, tdm commented
@zwliew yes, that was an oversight when Mike did the 14.1 changes to crackling.  Then he duplicated the work over to kipper.

2017-01-27 14:28 UTC, mikeNG commented
#7 is the correct fix, I pushed the wrong blobs :/

2017-01-27 14:28 UTC, closed without merging